### ISSUE TITLE
graalvm-js工程中未上传本地文件txt和js文件

### ISSUE THREAD

**Issue by liangmeng-gitlistener** [Harries/springboot-demo#2]
com.et.graalvm.js.JavaScriptFunction#file等方法需要依赖额外的js和txt文件，可以将这些文件放入resource下，并使用相对路径调用

com.et.graalvm.js.RemoteJSTest#main无法直接使用"https://example.com/script.js"这样的URL

**Comment by Harries** [comment]
> com.et.graalvm.js.JavaScriptFunction#file等方法需要依赖额外的js和txt文件，可以将这些文件放入resource下，并使用相对路径调用
> 
> com.et.graalvm.js.RemoteJSTest#main无法直接使用"[https://example.com/script.js"这样的URL](https://example.com/script.js%22%E8%BF%99%E6%A0%B7%E7%9A%84URL)

已经上传到resource目录下了  @liangmeng-gitlistener
